import Akun from './Akun'
import Home from './Home'
import Jobs from './Jobs'
import Login from './Login'
import Search from './Search'
import Signup from './Signup'
import Splash from './Splash'
import Upload from './Upload'
import detailPost from './Home/detailPost'
import ProfilePage from './ProfilePage'
import LikePages from './LikePages'
import BookmarkPages from './Bookmarkpages'
import FollowerPages from './FollowerPages'
import FollowingPages from './FollowingPages'
import EditPortfolio from './EditPortfolio'
import PostJob from './PostJob'
import detailJobs from './Jobs/detailJobs'
import EditProfile from './EditProfile'
import editPassword from './EditProfile/editPassword'
import editPhoto from './EditProfile/editPhoto'
import searchUser from './Search/searchUser'
import Activity from './ActivityPage'
import UserDetailJobs from './Jobs/UserDetailJobs'
import EditJob from './EditJob'
import ForgotPass from './ForgotPass'

export {Akun, Home, Jobs, Login, Search, Signup, Splash, Upload, detailPost, ProfilePage, LikePages, BookmarkPages, FollowerPages, FollowingPages, EditPortfolio, PostJob, detailJobs, EditProfile, editPhoto, editPassword, searchUser, Activity, UserDetailJobs, EditJob, ForgotPass}